version: '3.8'

services:
  userservice:
    build:
      context: ./UserService
    ports:
      - "5001:80"
    networks:
      - mynetwork
    volumes:
      - ./certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./certs/server.crt:/etc/ssl/certs/server.crt
      - ./certs/server.key:/etc/ssl/private/server.key

  productservice:
    build:
      context: ./ProductService
    ports:
      - "5002:80"
    networks:
      - mynetwork
    volumes:
      - ./certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./certs/server.crt:/etc/ssl/certs/server.crt
      - ./certs/server.key:/etc/ssl/private/server.key

  orderservice:
    build:
      context: ./OrderService
    ports:
      - "5003:80"
    networks:
      - mynetwork
    volumes:
      - ./certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./certs/server.crt:/etc/ssl/certs/server.crt
      - ./certs/server.key:/etc/ssl/private/server.key

  notificationservice:
    build:
      context: ./NotificationService
    ports:
      - "5004:80"
    networks:
      - mynetwork
    volumes:
      - ./certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./certs/server.crt:/etc/ssl/certs/server.crt
      - ./certs/server.key:/etc/ssl/private/server.key
      
  authservice:
    build:
      context: ./AuthService
    ports:
      - "5005:80"
    networks:
      - mynetwork
    volumes:
      - ./certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./certs/server.crt:/etc/ssl/certs/server.crt
      - ./certs/server.key:/etc/ssl/private/server.key

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./certs/ca.crt:/etc/rabbitmq/ca.crt
      - ./certs/server.crt:/etc/rabbitmq/server.crt
      - ./certs/server.key:/etc/rabbitmq/server.key

networks:
  mynetwork:
    driver: bridge
